### ISSUE TITLE
Update to NestJs 8.0

### ISSUE THREAD

**Issue by mihai-osvat** [BeerMoneyDev/nest-qldb#12]
Hi,

Installing the **nest-qldb** library along with **nestjs/core@8.0.4** throws errors like:

`npm ERR! Could not resolve dependency:
npm ERR! peer @nestjs/core@"^7.0.0" from nest-qldb@2.3.0
npm ERR! node_modules/nest-qldb
npm ERR!   nest-qldb@"*" from the root project`

Could we please have a newer version ?

Thanks.

**Comment by benMain** [comment]
@mihai-osvat I'll look at this this weekend. Or you're welcome to fork and have us review.

**Comment by mihai-osvat** [comment]
Hello,

I created a pull-request from my forked repo.

Thanks.

**Comment by mihai-osvat** [comment]
Hello again, could you please have a look at my PR ?

**Comment by mihai-osvat** [comment]
any news ?

**Comment by elicobanksbridge** [comment]
I am also looking for nest-qldb support for nestjs 8
I will appreciate if you can update me when do you expect it to be released ?

**Comment by benMain** [comment]
@elicobanksbridge We're working on it now.

**Comment by benMain** [comment]
@mihai-osvat So you need to use ng-changelog convention. I'm going to major version this to protect people on nest 7 using `^`

**Comment by benMain** [comment]
@mihai-osvat @elicobanksbridge This has been released at https://www.npmjs.com/package/nest-qldb/v/3.0.0. Closing this issue.
