### ISSUE TITLE
Error: Cannot find module '@aws-sdk/smithy-client'

### ISSUE THREAD

**Issue by yangricardo** [BeerMoneyDev/nest-qldb#21]
I noticed that this package `@aws-sdk/smithy-client` is required indirectly by `nest-qldb`, for a time, i have installed this `@aws-sdk/smithy-client` or `@aws-sdk/node-http-handler`.  And this works, but maybe a update from oficial aws qldb dependencies works. 

 Even with my workaround of installing the dependencies on my project, seems both [`@aws-sdk/smithy-client`](https://www.npmjs.com/package/@aws-sdk/smithy-client) [@aws-sdk/node-http-handler](https://www.npmjs.com/package/@aws-sdk/node-http-handler) is now deprecated. Note that this issue of module not found causes issues when i run nestjs in development and production modes, not build...
![image](https://github.com/BeerMoneyDev/nest-qldb/assets/5523565/7636498c-e123-4e96-b723-2ad0b67bf07b)

**Comment by makergabriel** [comment]
Moved to peer dependencies with latest version - https://github.com/BeerMoneyDev/nest-qldb/releases/tag/v3.0.4

**Comment by benMain** [comment]
@yangricardo handled through peerDependencies
